apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  selector: 
    app: my-nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

  